apiVersion: 1

datasources:
-  name: PostgreSQL
   type: postgres
   url: postgres:5432
   database: project
   user: airflow
   isDefault: true
   id: 1
   uid: 'ss7OIvt4z'
   orgId: 1
   secureJsonData:
      password: 'airflow'
   jsonData:
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 0 # Grafana v5.4+
      maxIdleConns: 2 # Grafana v5.4+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 1300 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false